[package]
name = "hikari-theme"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[features]
default = ["scss"]
scss = []       # Default SCSS compilation

[dependencies]
# Workspace dependencies
hikari-palette = { path = "../palette" }

# MCP / network and protocols
dioxus.workspace = true
