[package]
name = "hikari-builder"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
grass = "0.12"
serde = { workspace = true, features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"

[build-dependencies]
grass = "0.12"
serde = { workspace = true, features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
