[package]
name = "hikari-icons"
version = "0.1.0"
edition = "2021"

[build-dependencies]
hikari-builder = { path = "../builder" }

[dependencies]
# MCP / network and protocols
dioxus = { workspace = true }

# WASM dependencies (only for web target)
[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = { workspace = true }
web-sys = { workspace = true }
wasm-bindgen-futures = "0.4"
